# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [9]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def get_integer_input(message):
    """
    This function will display the message to the user
    and request that they input an integer.
    If the user enters something that is not a number
    then the input will be rejected
    and an error message will be displayed.
    The user will then be asked to try again."""
    value_as_string = input(message)
    print(value_as_string)
    while not value_as_string.isnumeric():
        print('The input must be an integer')
        value_as_string = input(message)
    return int(value_as_string)

def permutations(dim):
    """
    This function make permutation list
    """
    m = []
    for i in range(dim):
        m.append(i)
    perm_list = list(itertools.permutations(m, dim))
    return perm_list

def sing(perm_list):
    """
    This function count number of invertion that had done
    for permutation list
    """
    sing_list=[]
    for tuples in perm_list:
        perm_count = 0
        for i in range(0,len(tuples)):
            for j in range(i, len(tuples)):
                if tuples[i] > tuples[j]:
                    perm_count += 1
        if perm_count % 2==0:
            sing_list.append(1)
        elif perm_count % 2 == 1:
            sing_list.append(-1) 
    return sing_list

def result_fin(matrix, perm_list, sing_list):
    """
    This fucntion find all matrix element we need to sum and change to nesseseri sing and then sum it up
    """
    prod_list = []
    for tuples in perm_list:
        pr = 1
        for i in range(dim):
            pr = pr* matrix[i][tuples[i]]
        prod_list.append(pr)
    for i in range(len(prod_list)):
        prod_list[i]=prod_list[i]*sing_list[i]
    return sum(prod_list)


dim = get_integer_input('Enter dim: ')
matrix = random_matrix(dim)
perm_list = permutations(dim)
sing_list = sing(perm_list)

result = result_fin(matrix, perm_list, sing_list)

print(matrix)
print('det =', result)
print('det numpy =', np.linalg.det(matrix))

    

3
[[7 7 7]
 [7 5 7]
 [1 5 3]]
det = -28
det numpy = -27.999999999999996
